package br.com.ericsoares.builders;

import br.com.ericsoares.entities.Usuario;

public class UsuarioBuilder {
	
	// AS CLASSES BUILDER AJUDAM AMPLAMENTE PARA DIMINUIRMOS A QUANTIDADE DE CODIGO DIGITADO E MELHOR LEGIBILIDADE.
	// ISSO ATRAVEZ DE SIMPLIFICARMOS A QUANTIDADE DE INSTACIACOES QUE PRECISAMOS FAZER. SIMPLESMENTE CRIAMOS UM BUILDER, CORRESPONDENTE A CLASSE QUE E MUITO INSTANCIADA. 
	// SENDO ASSIM, NESSE BUILDER, IREMOS JA FAZER TODA INSTANCIACAO NECESSARIA. ALEM DE PODERMOS ADICIONAR OUTROS METODOS PARA MODFICAR A INSTANCIACAO PADRAO, CASO SEJA NECESSARIO.

	private Usuario usuario;
	
	private UsuarioBuilder() {}; // O CONSTRUTOR SERA PRIVADO, POIS, ELE JA SERA INSTANCIADO NO PROPRIO METODO DE CRIACAO DO OBJETO. ALEM DE IMPEDIRMOS O ACESSO DELE POR OUTRAS CLASSES
	
	public static UsuarioBuilder umUsuario() { 					// ESSE SERA NOSSO METODO PADRAO DE INSTACIACAO, QUE NO CASO E DE UM USUARIO. AO INVES, DE TERMOS QUE INSTANCIAR ELE SEMPRE COM Usuario usuario = new Usuario()
		UsuarioBuilder builder = new UsuarioBuilder();			// SIMPLESMENTE CHAMAMOS ESSE METODO, E ELE JA IRA INSTANCIAR A CLASSE DESEJADA.
		builder.usuario = new Usuario();
		builder.usuario.setNome("Usuario 1 ");
		return builder;
	}
	
	public Usuario agora() {
		return usuario;
	}
	
}
